version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: '14.15'
      - aws-cli/setup
      - eb/setup
      - run:
          name: Angular CLI
          command: |
            npm i -g @angular/cli
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End TEST
          command: |
            npm run frontend:test
     - run:
          name: Back-End TEST
          command: |
            npm run backend:test
      - run:
          name: Deploy FRONT-END App
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy BACK-END App
          command: |
            npm run backend:deploy
workflow:
  udagram:
    jobs:
      - build